name: PR Summary Generator
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR diff
        id: get-diff
        run: |
          git fetch origin ${{ github.base_ref }}
          DIFF=$(git diff origin/${{ github.base_ref }}...HEAD)
          echo "DIFF<<EOF" >> $GITHUB_ENV
          echo "$DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Generate Summary
        id: summary
        uses: actions/github-script@v7
        env:
          INFERENCE_API_URL: ${{ vars.INFERENCE_API_URL}}
          INFERENCE_API_KEY: ${{ secrets.INFERENCE_API_KEY }}
        with:
          script: |
            const { OpenAI } = require("openai");
            const openai = new OpenAI({
              baseURL: process.env.INFERENCE_API_URL
              apiKey: process.env.INFERENCE_API_KEY,
            });

            const diff = process.env.DIFF;
            
            const completion = await openai.createChatCompletion({
              model: "meta-llama/llama-3.1-70b-instruct",
              messages: [{
                role: "system",
                content: "You are a helpful assistant that summarizes git diffs. Be concise and focus on the key changes."
              }, {
                role: "user",
                content: `Please summarize these changes:\n${diff}`
              }],
            });

            const summary = completion.data.choices[0].message.content;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## 🤖 Automated PR Summary\n\n${summary}`
            });